version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:20"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/apps/flutter_app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:40"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 10
